### ISSUE TITLE
Focus after move in layouts

### ISSUE THREAD

**Issue by mohanzhang** [jigish/slate#103]
I've been creating layouts to simulate an xmonad workflow by binding 1:cmd to move and resize preset windows for certain apps into place as "workspace 1" and so forth up to 9. What's missing (or, what I have missed) is the ability to bring the windows that are part of a layout to the front as they are being moved. Does anyone know of a way to achieve this effect?

**Comment by jigish** [comment]
I currently don't support focus ordering in layouts but it sounds like something that could be useful. I'll think of a way to add this in.

**Comment by mohanzhang** [comment]
Hey Jigish - thanks for the time and effort that you put into Slate. I actually felt strongly enough about this issue that I'd thought I'd at least try to hack something together for myself (it's the last thing preventing me from having a minimally viable xmonad substitute on OSX--at least in the way that I personally use xmonad).

Is there any documentation available for those wishing to contribute? I figured I could just load this project into xcode and build it, but I'm getting errors about undeclared identifier __bridge all over. Not sure if that's because I'm using xcode 3.2.6 or if I'm doing something really wrong. I have never built an xcode project before, so it's entirely possible that I need to do some reading to get up to speed. I thought I'd do a sanity check with you first, though. Thanks.

**Comment by jigish** [comment]
O boy. To be completely honest I never expected slate to gain the popularity it has lol. I built it mainly for myself as a replacement to Divvy because at the time Divvy couldn't move windows across monitors and it kind of spiraled into what it is today from there. As far as documentation to build it, I unfortunately don't have any. Nor do I have any documentation in the code (though I have a couple issues for myself to add documentation and unit tests - #97 and #98).

As far as building goes -- You need to get the latest Xcode. Slate uses ARC which is why you're getting all the undeclared identifier __bridge all over the place. Thats an ARC specific directive that tells the compiler that the code I am referencing is non-ARC. Once you get the latest Xcode, the target "Slate" should build it. I also have a ruby script that can generate the .tar.gz and the .dmg in script/slate.rb. Basically run `script/slate.rb gen` and it will generate everything and throw it into the build/Release folder. There are some dependancies though (one of which is a git submodule) so you may need to look through the script and make sure you have it all.

Sorry I can't be of more help. I'm trying to get things documented but slate has grown to a size that it is a pretty large task now lol.

**Comment by mohanzhang** [comment]
No worries--I totally understand. That's kind of what you get for appearing on the frontpage of HN with a free, easy-to-use, open-source project that solves a real problem for a bunch of rabid devs :)

Anyway, it turns out that in order to get the latest xcode, I need to upgrade from Snow Leopard. I'm not convinced that I want to do that right now, so I'll have to temporarily retract my enthusiasm for implementing this feature myself. I'll have to revisit the idea after I figure out whether I want to upgrade to Mountain Lion. Thanks again for all the good work!

**Comment by paddykontschak** [comment]
@mohanzhang Xcode 4.2 is/was available for Snow Leopard. Apple was so _nice_ to remove it from their servers but you can find it on [TPB](http://thepiratebay.se/torrent/6721955/). I realize that not everyone is a friend of torrents but in this case Apple is not even helping developers on old OS X versions anymore.

**Comment by mohanzhang** [comment]
Thanks @paddykontschak - For the record, I neither deny nor acknowledge the existence of this torrent.

@jigish But suppose hypothetically that I got Xcode 4.2 via some means and then tried to build the project again. I'd, uh, _probably_ get errors like the following:

.../slate/Slate/SlateAppDelegate.m:36:13: error: existing ivar 'currentHintOperation' for unsafe_unretained property 'currentHintOperation' must be __unsafe_unretained [4]

Any idea what that means? Is there some setting I'm missing somewhere?

**Comment by jigish** [comment]
hmm. thats a good question. I'm using Xcode 4.5 so i'm not getting that error. From what I can tell it would be complaining about how the properties are declared for some reason. Probably adding something like `(strong)` after `@property` would fix it. This would be a problem most likely fixed by Apple's compiler upgrades since 4.2.

**Comment by mohanzhang** [comment]
I think you're right. Adding (strong) made the error go away. I read briefly about the issue and it does seem that there was a change in ARC in later versions of Xcode. Xcode 4.2 starts out with 7 errors initially, but as files compile successfully after being fixed in the above way, those lower in the dependency chain that were previously not touched then start giving similar errors, creating a cascade of errors that will take forever (or "too long for me" :p) to fix.

Well ok, I guess it's back to the Snow Leopard vs Mountain Lion internal debate. Not to turn this into a os-war tangent, but it does kind of suck that with Apple's recent directions, there is no longer a clear choice for best OS anymore :(

In the off-chance I decide to go for the upgrade, here's the basic design I considered:
- Add a new config called "focusOnLayoutOperation" that can be true or false
- Inside activateLayout in LayoutOperation.m, check for the config value and if true, iterate windowsArrRef and bring each one into focus

Of course, I have no clue if there are any details that disqualify this design since I haven't looked too closely, but would you say something like that is reasonable?

**Comment by jigish** [comment]
So actually I thought it would be kind of elegant to use the ordering of the directives in the .slate file to be the order in which the windows are focused. So the last one specified would be the last focused and therefore the one that is focused at the end of the layout operation. This way we have consistent behavior regardless of what order the windows are in windowsArrRef. I actually may get around to this today so you may not have to worry about Snow Leopard vs Mountain Lion until later in the future :)

**Comment by jigish** [comment]
This is done. Will be in version 1.0.7 when I push it. The config is called `layoutFocusOnActivate`. I like the first word in the config name to be the operation it touches so it is a bit easier to figure out what they do.

Basically, if set to true, it will focus all windows that the layout operation touches in the order that it touches them. The order will be the order in which the applications are configured in the .slate file.

**Comment by mohanzhang** [comment]
Nice! Many thanks!
