### ISSUE TITLE
add new `sequence` operation

### ISSUE THREAD

**Issue by SethMilliken** [jigish/slate#114]
An operation similar to `chain`, but simpler in that it allows a binding to execute all pipe-delimited operations sequentially in a single invocation.

USE CASE: A `throw` operation that both resizes _and_ repositions the window.

EXAMPLE: with the proposed `sequence` operation:

```
alias right-half push right bar-resize:screenSizeX/2
bind 2:cmd,ctrl sequence throw next | ${right-half}
```

I could imagine useful scenarios involving adding a `nudge` a `focus` or even a `hint` to a sequence, too (e.g. throw the current window to another screen and then focus a window that had been obscured by the moved window in preparation for the next operation).

An `IGNORE_FAIL` option would probably be appropriate for this, as well.

**Comment by jigish** [comment]
Sounds like a good idea.

The issue with doing this with something like `hint` is that `hint` breaks the current event loop while waiting for the input so you'd have to restrict `hint` to being the last operation.

Either way I like it and I'll try to implement it soon. Should be pretty easy because the basis is already there with the `chain` operation

**Comment by jigish** [comment]
Done. will be in 1.0.6 which I'm pushing shortly
