### ISSUE TITLE
Lost ability to navigate lines of text

### ISSUE THREAD

**Issue by ocxo** [jigish/slate#189]
I want to use Slate. The main barrier for me right now is that when I use it I can't use alt+left/right to move between words in a text block. cmd+left/right doesn't move me to the beginning/end of a line. Even fn+left/right is disabled.

Am I doing something wrong? I'm using the default slate configuration. I want to use this but the loss of navigating bits of text via keyboard is more frustrating than not being able to resize windows via keyboard.

**Comment by josh-** [comment]
The beauty of Slate is that it's completely customisable, so you can set all the keybindings yourself - the default config does indeed take over your alt+left/right and cmd+left/right, which is why you're missing out on standard OS X text selection.

You should create a new file in your home directory called `.slate` and then start adding your own bindings there.

Alternatively, you can copy the default config to your home directory and make changes as needed, which can be done by running the following command:

``` bash
curl https://raw.github.com/jigish/slate/master/Slate/default.slate > ~/.slate
```

**Comment by jigish** [comment]
@josh- is correct. Using the default `.slate` file you'll lose a lot of those bindings. If you want to remove them or change them copying the `default.slate` to `~/.slate` is the way to go. You can then mess with the bindings yourself and update them to whatever you want.
