### ISSUE TITLE
Random crashing and keyboard shortcut lag

### ISSUE THREAD

**Issue by aaronlifton3** [jigish/slate#202]
What happened to my favorite app?  :worried:

**Comment by jigish** [comment]
Are you using AppTamer by any chance? Or is another app not responding? There is currently an issue where Slate will hang when any app is non responsive because it keeps track of window positions in the background. Working on fixing that but if you're using AppTamer an easy fix would be to not use it until I fix Slate to play nice with it.

**Comment by aaronlifton3** [comment]
Not using AppTamer. I simplified my .slate config and it seems to be running perfectly now. Excited to try the new features :)
