### ISSUE TITLE
Crash caused by AXObserverCreate error

### ISSUE THREAD

**Issue by mgax** [jigish/slate#206]
I was running Slate from within Xcode and it hit upon the following error.
At [RunningApplications.m line 382](https://github.com/jigish/slate/blob/master/Slate/RunningApplications.m#L382) `AXObserverCreate` returned error code `-25201` (`kAXErrorIllegalArgument`) and `observer` remained `NULL`. Since there error code is not checked, the following call to `AXObserverAddNotification` crashes Slate.

**Comment by jigish** [comment]
weird. the observer should never be null unless slate was started and accessibility was off. but then in that case slate would have shown an error. either way i'll do a null check :)

**Comment by mgax** [comment]
No, accessibility was on, this crash occurred after running for some time, doing operations. Maybe there's a race condition with an application starting and stopping immediately, or something of that sort.

**Comment by ealimonda** [comment]
I can confirm this crash in `AXObserverAddNotification`. It seems to be reproducible with a very high chance if you're launching an application that quits right away.

An application similar to the following (it's a small wrapper I'm using in order to fix some shortcomings of [MultiBrowser](https://sites.google.com/site/tesseractsoftware/multibrowser)), will cause Slate to crash almost everytime you launch it (`open -a MyTestApp http://example.com`):

```
@implementation MBLAppDelegate
- (void)applicationWillFinishLaunching:(NSNotification *)notification {
    [[NSAppleEventManager sharedAppleEventManager] setEventHandler:self andSelector:@selector(handleURLEvent:withReplyEvent:) forEventClass:kInternetEventClass andEventID:kAEGetURL];
}
- (void)handleURLEvent:(NSAppleEventDescriptor*)event withReplyEvent:(NSAppleEventDescriptor*)replyEvent {
    NSString* url = [[event paramDescriptorForKeyword:keyDirectObject] stringValue];
    [[NSWorkspace sharedWorkspace] openURLs:@[[NSURL URLWithString:url]]
                    withAppBundleIdentifier:@"com.TesseractSoftware.MultiBrowser"
                                    options:NSWorkspaceLaunchDefault
             additionalEventParamDescriptor:nil
                          launchIdentifiers:NULL];
    [NSApp terminate:self];
}
@end
```

The issue is, of course, fixed if the return value of `AXObserverCreate` is checked against `kAXErrorSuccess`.

**Comment by jigish** [comment]
fixed. will push a new version sometime today.
