### ISSUE TITLE
vertical window placement wrong

### ISSUE THREAD

**Issue by thomasjachmann** [jigish/slate#224]
bind esc:cmd move 0;screenSizeY_0.5 screenSizeX;screenSizeY_0.5 1

I'd expect this to place the window on the lower half of the screen, but it actually places the window's content on that location. The window's title bar sticks up into the upper half of the screen leaving a gab of the window's title bar's height below the window. Or am I doing something wrong here?

**Comment by jigish** [comment]
Couple comments and questions:
1. it really should be `bind esc:cmd move screenOriginX;screenOriginY+screenSizeY*0.5 screenSizeX;screenSizeY*0.5 1` because `0,0` is the top-left of the main screen (the one with the menu bar). it is always a good idea to use `screenOriginX` and `screenOriginY` because they take into account multiple monitors, the dock, the menu bar and such.
2. What application is this? When you say "the window's title bar sticks up into the upper half of the screen" can you manually (with your mouse) move the title bar off the window's content? If so, they are likely two different windows.
3. Can I get a before and after screenshot please? It will help me better understand what is happening.

**Comment by thomasjachmann** [comment]
1. OK, so it's a user error. Using screenOrigin is reasonable.
2. Any application, eg Finder. Maybe I put it wrong. With "sticking up" I just meant that the window is placed a bit too high and by roughly the height of the title bar.
3. No need to further investigate in this, it really was a misunderstanding on my part, sorry for the hassle.

Thanks so much, slate is boosting my productivity immensely and it is just fun to configure. OK, the last part kills productivity again, since I'm playing around with it so much. ;)
