### ISSUE TITLE
Slate needs some kind of log to be easier to debug

### ISSUE THREAD

**Issue by deiga** [jigish/slate#242]
Hi, 
I seriously think that slate needs some kind of log that will tell me if there were any errors in parsing the .slate and what happens when pressing keys. It's frustrating to notice that some bindings simply don't work and not know why or what to do about it.

**Comment by coddingtonbear** [comment]
Have you noticed `slate.log` (https://github.com/jigish/slate/wiki/JavaScript-Configs)?  It allows you to send messages to OSX's console.

**Comment by jigish** [comment]
yes, if you're using the JavaScript configs then `slate.log` is the way to go. Otherwise you can also clone the repository and use the Debug version of slate. That throws all sorts of logs to the Console. What issues in particular were you seeing? If a binding does not parse properly it should throw up an alert.

**Comment by deiga** [comment]
@jigish I've just noticed that my .slate.js doesn't load at all, or at least bindings don't work and S.log doesn't either. Could you look at it and tell me if there's something wrong? It used to work last week or so..
https://github.com/deiga/dotfiles/blob/master/slate.js

**Comment by stdavis** [comment]
@deiga I'm having the same problem with my .slate.js not loading at all. Did you ever get it resolved?

**Comment by deiga** [comment]
Nope, I never figured out what was wrong. I still think it's the string catenation thing-y. But I just moved my commands over to .slate for the time being
