### ISSUE TITLE
Can't get binding for relaunch to work

### ISSUE THREAD

**Issue by deiga** [jigish/slate#243]
I've got the following settings
- ~/.slate

```
alias hyper ctrl;shift;alt;cmd
bind r:${hyper} relaunch
```
- ~/.slate.js

```
S.bnda({

  // Relaunch
  "r:ctrl;shift;alt;cmd" : S.op("relaunch")
});
```

Neither one has any effect, but it also doesn't report any errors.

BTW: how do I bind keys and aliases in the javascript files? Like this?

```
var foo = ...
S.bind('r:'+foo,..);
```

**Comment by jigish** [comment]
Just tried

``` javascript
S.bnda({

// Relaunch
"r:ctrl;shift;alt;cmd" : S.op("relaunch")
});
```

And it worked fine for me. Are you sure it isn't working? The relaunch is silent and the only way to know it happened for sure would be to put a log in your `.slate.js`

To the second point - yes. Since javascript is a full language, I didn't implement any sort of alias. I figured if you want aliases you can just define a variable :). So your relaunch would be:

``` javascript
var hyper = "ctrl;shift;alt;cmd";
S.bnd("r:"+hyper, S.op("relaunch"));
```

Also tried that and it does the relaunch as well.

If yours is definitely not working what is your OS X version?

**Comment by deiga** [comment]
Oh, I figured out my problem and it actually had nothing to do with slate :) I had remapped my keys in a way which prevented left shift and left side keys to be used :P
