### ISSUE TITLE
OSX Yosemite Compatibility

### ISSUE THREAD

**Issue by julesmoretti** [jigish/slate#428]
Hello, just upgraded from 10.9 and it seems to have stopped responding. Any advice? Thank you.

**Comment by julesmoretti** [comment]
Just some more info, I tried with a .slate and just now .slate.js but that did not work either.

**Comment by Dayjo** [comment]
Same as that. If I Relaunch I get the following pop up;
![](http://cl.ly/image/161f1B2k033K/Image%202014-10-17%20at%2011.19.43%20am.png)

When I click 'Enable' it does nothing, however I already have it set up to allow accessibility;
![](http://cl.ly/image/1g1c1u1Z310t/Image%202014-10-17%20at%2011.21.04%20am.png)

## UPDATE

I closed Slate complete, deleted it from my Accessibility list, relaunched it, clicked Enable when it asked me the above, then went back into accessiblity and checked the box next to Slate.

It now works.

**Comment by mattdw** [comment]
All I needed to do to fix this problem was to uncheck it and then immediately recheck it (in the "accessibility" list.)

**Comment by MuschPusch** [comment]
Thanks mattdw! That indeed works fine :)

**Comment by vbfischer** [comment]
Uncheck/recheck did it for me too.  Thanks.

**Comment by tsabat** [comment]
:+1:

**Comment by julesmoretti** [comment]
You guys rule! Cheers and happy Slating!

**Comment by wahn** [comment]
Uncheck/recheck did it for me too. Thanks.

**Comment by fbrinker** [comment]
Thanks worked for me

**Comment by mheuser** [comment]
Worked for me too. But had to search a bit for the "Accessibility list". To get there you have to open System Preferences -> Security and Privacy -> Tab Privacy -> Accessibility.

**Comment by swieder227** [comment]
@mheuser thanks for the tip.

Confirming that un-checking and immediately re-checking worked on 10.10.2 fresh install.

**Comment by loshlee** [comment]
For me, the 10.10.2 system fixes the problem, except that the problem isn't always fixed by reaching 10.10.2 through the upgrade process. In other words, I had to fix it by doing an in place installation of 10.10.2 rather than upgrading through the incremental 10.10.2 update. In previous versions of OS X, I've been able to apply the combo update to any previous or current version of the same OS, but the Yosemite combo updater doesn't allow me to select a 10.10.1 or  10.10. 2 system as a target. This limitation disappoints me, because applying the combo update for the current OS release has for a very long time provided the simplest repair procedure for certain problems.

**Comment by knightjp** [comment]
Every time I restart my computer, i get the message, 
![screen shot 2015-09-19 at 5 25 46 pm](https://cloud.githubusercontent.com/assets/14360736/9976390/a0e27faa-5ef3-11e5-9474-b206f58985d2.png)
I'm not sure what is going on and where should I be posting the .slate file. I have one in my home directory just as the instructions state.
