### ISSUE TITLE
The hint letters change based on which window is focused

### ISSUE THREAD

**Issue by philc** [jigish/slate#51]
On my screen, I have 3 windows from left to right, with the first one focused. The hints are A B C.

If I focus the second window, the hints are B A C. The hint letters change depending on which window is focused. I think it will be less disturbing if the hints had a stable ordering from left to right across the screen (i.e. the leftmost window is always A).

**Comment by jigish** [comment]
This is because the order in which I get windows from the API. As a result of the switch operation I may add a constantly updating global list of windows sorted by which window was activated the last. In this case, I should be able to attach a hint letter to every window and keep it the same throughout its lifetime. This would also allow me to save time calculating which hint should be attached to which window which may make the hint operation faster.

**Comment by philc** [comment]
IMO, sorting that list by the window's X and Y would be more usable than giving each window a consistent hint, because particular windows churn all the time, but "the left half of my screen" stays constant.

**Comment by jigish** [comment]
I can agree with that, but the problem I see is even though the "left half of my screen" remains constant the number of windows will always be changing. Thus if I choose to anchor the "beginning" of the window list to the left side of the screen, the hint for the rightmost window will be constantly changing while the hint for the leftmost window will be constant. That seems sort of silly. If I keep the hint tied to the specific window over its lifetime it may be a bit more intuitive, as at least for me I think of the content of each window rather than its location when I want to switch to it. So if I tie, for example, the terminal running my rails to "b" and I think to myself "I need to focus my rails terminal" it seems a bit more natural to just be able to hit "b" again to get to it if I've already done that once.

For now, though, keeping track of windows over their lifetime is part of the switch operation's task which will take a bit more time. So I'll implement the left-to-right ordering as a config as I still feel it would get a bit counterintuitive at times.

**Comment by jigish** [comment]
also as a side note, the more windows that are open, the more overhead the left-to-right version will add as I'll have to sort the windows based on x and y coords before I can hint them. hopefully it won't reduce performance too much.

**Comment by jigish** [comment]
added `windowHintsOrder` config.

`config windowHintsOrder leftToRight`

or

`config windowHintsOrder rightToLeft`

or

`config windowHintsOrder none`

default is `none`.

will be generating 0.4.19 with this fix in the next couple of minutes.

**Comment by jigish** [comment]
also - performance impact seems to be minimal
