### ISSUE TITLE
Switching desktops breaks window hints

### ISSUE THREAD

**Issue by philc** [jigish/slate#59]
Steps to reproduce:
1. Launch slate
2. Hit the hint key; see hints
3. Switch virtual desktops
4. Switch back
5. Hit the hint key; no hints are shown

Version 0.5.1.

**Comment by jigish** [comment]
great. apparently the accessibility API returns only the windows that are active on the current desktop. So my keeping track of windows and such breaks with virtual desktops because when you switch desktops I prune all windows since all apps report that they have no windows open. I'm going to have to rethink how to do this to support spaces. It may take some time.

**Comment by jigish** [comment]
Switching to version 1.1 as this will take some time. I want to get Slate on the App Store first, then I'll fix this.

**Comment by jigish** [comment]
This should be fixed. Well, at least it doesn't break now by default.
