### ISSUE TITLE
"Could not load ~/.slate"

### ISSUE THREAD

**Issue by simpleshadow** [jigish/slate#83]
I'm using OSX 10.8.1. I have the [default.slate](https://github.com/jigish/slate/blob/master/Slate/default.slate) in `~/`. Any idea what could be wrong? Excited to test this out.

![Error](http://f.cl.ly/items/2t2b1j2M0k0P2z1H0Q36/Screen%20Shot%202012-09-07%20at%209.34.22%20AM.png)

**Comment by jigish** [comment]
So I haven't gotten around to testing on Mountain Lion yet unfortunately, but I don't think I've used any Deprecated APIs so it should work fine. Either way here are a couple possible issues that may cause this:
1. Make sure to rename "default.slate" to ".slate"
2. Make sure it is in ~/ (this part you say you have)
3. Make sure the file's permissions include read

Also, this message is just a warning. You _can_ click continue and it will automatically load the default slate file so you can try it out. It'll just get irritating because every startup will show this message.

And finally, be sure to disable (or change) the bindings that expose and such use because I _think_ the default slate file uses the same bindings (you can check yourself, it should be decently commented)

Let me know if this helps or not. If not, I can try upgrading my box to Mountain Lion tonight to see if I can repro.

**Comment by simpleshadow** [comment]
Thanks @jigish! Issue resolved. I failed step 1. :D

Appears to be working ok on Mountain Lion. I'll play with it a bit more and let you know how things go.
