### ISSUE TITLE
Implement if/else statements

### ISSUE THREAD

**Issue by paddykontschak** [jigish/slate#91]
I'm currently working on a way to resize my browser to 4 common widths in responsive design, 980, 768, 480 and 320. I also want the browser to center in the middle of the screen.

```
alias nine (1680-980)/2
[...]

bind h:cmd;ctrl;alt move ${nine};76 980;807
[...]
```

That works on my main computer. The problem I'm facing is that I have 2 Macs with different screen resolutions but I want to keep the key binding the same on both Macs. What I need is an if/else statement, like so:

```
alias nine-big (1680-980)/2
[...]

alias nine-small (1280-980)/2
[...]

if screen === 1680x1050
  bind h:cmd;ctrl;alt move ${nine-big};76 980;807
  [...]
else if screen === 1280x900
  bind h:cmd;ctrl;alt move ${nine-small};76 980;707
  [...]
```

**Comment by paddykontschak** [comment]
I realized that I could solve my problem with screenSizeX.

I think the idea is still worth a discussion though.

**Comment by jigish** [comment]
I have been thinking about if/else for a while. Seems like a good idea but the question is what would the conditional of the if be? If we can come up with a good use case I have no problem adding it. I'd just rather spend my time on other things (Spaces support, run in background, etc) if we can't come up with a use case :)

**Comment by wez** [comment]
Have you considered just embedding something like Lua for the configuration file and using that instead of a custom parser?  I have experience with this and can put something together as an example if you're not opposed to it.

**Comment by jigish** [comment]
I actually have not. That seems like a good idea as I can push the parsing into a library and not worry about, but I'm not terribly familiar with Lua. I'd be down to learn. If you want to throw together as an example I can take a look and see what I can do. Obviously I'd have to support both styles (or have a old to new converter) for it to be viable.

**Comment by wez** [comment]
I'll work up an example and send you a pull request.  I have a couple of others outstanding, so expect a couple of contributions by the weekend.

**Comment by muescha** [comment]
How about to use ruby for configuration file?

**Comment by v-yarotsky** [comment]
I think conditionals would allow to have same key binding for 'push' and 'throw' if already pushed, like this:

```
alias pushed-right windowTopLeftX == (screenOriginX + screenSizeX / 2) && 
  windowTopLeftY == (screenOriginY + screenSizeY / 2) && 
  windowSizeX == screenSizeX / 2 && 
  windowSizeY == screenSizeY / 2

bind right:f13 if ${pushed-right} throw next; else push right bar-resize:screenSizeX/2
```

I could also help implementing a ruby DSL for configuration file :)

**Comment by trishume** [comment]
+1 for Ruby. Slate is already the best thing ever (thank you @jigish!) but Ruby integration would combine the two best things ever for maximum bestness.

Although using Lua would make me just as happy and would be 10000x times easier to implement. Ruby will not be easy to embed until mruby comes out. Lua is probably a better solution but Ruby would be super cool.

**Comment by jigish** [comment]
ruby eh? that sounds like fun. I'll try look into this soon. As I've been posting on other issues, I've been rather busy lately. I probably won't be able to get to this for at least another week. I'm completely open for someone to start looking into this if they have time.

**Comment by trishume** [comment]
I've looked into this and ruby/macruby seems a bit hard. Some other language possibilities are lua and Nu (an obj-c lip dialect).

**Comment by trishume** [comment]
I also think that if scriptable configs are implemented they should be used to fix issue #101. Also, typo, Nu is a dialect of _lisp_, Which interestingly would make slate feel like emacs.

The main question for scripting is should it be an extra directive or should the entire config be a DSL? DSL offers more flexibility and in the long run makes adding config options easier but breaks existing config files.

**Comment by muescha** [comment]
please not so cryptic languages :-(

i think ruby is more easy to understand for non tech users

PS:
i really miss a GUI for the settings

**Comment by qmx** [comment]
as much as I love Ruby, it will just make the executable bigger. lua looks like the way to go :)

**Comment by mgax** [comment]
There's also Python, which is quite easy to embed. Keep in mind that MacOS ships with both Ruby and Python, so it's just a question of loading up the framework, and using their embedding APIs.

Some time ago I actually embedded Python with slate; it's probably easy to rebase the patch onto the current `master`: https://github.com/mgax/slate/tree/python.

**Comment by qmx** [comment]
@mgax out of curiosity, I've started to do the lua version here: https://github.com/qmx/slate/tree/lua_support, using cocoapods to manage the dependency

**Comment by jigish** [comment]
couple of thoughts (mainly so I don't forget myself):
1. if we're going to embed ruby/python/lua I'd like to do it right. e.g. you should be able to run the if/else _while_ the binding is activated. So you could use the current values of the window/screen/etc to change what you want to do with the particular binding in real-time. Like what @v-yarotsky commented.
2. I do _not_ want to shell out to achieve this. that would have horrible performance. As such I need a language with an interpreter that I can bind directly into objective-c. For example: what @mgax has done in his python branch.

I'm going to try to look into this today/tomorrow most likely and hopefully come out with a decision on the language to use going forward. Right now Python/Lua seem like the easiest to embed. Though I personally prefer Ruby so if I can find a good way to embed it I'll probably try that.

Also, if I do this, I'm going to try to revamp the documentation/wiki as part of the process since most of the syntax will change as a result.

And finally, I will obviously keep backwards compatibility with the current config syntax.

**Comment by mgax** [comment]
I updated my [branch](https://github.com/mgax/slate/tree/python). It understands a new configuration key, `pythonScript`, and a new operation for binding, `python`. So whenever the binding is triggered, it calls the named Python function from the script.

From within Python code, you have access to the Objective-C runtime, so you can call into Slate's classes. Here's how to use it: https://gist.github.com/4162837.

Something similar should be feasible for Ruby, there are equivalent [bindings](http://en.wikipedia.org/wiki/RubyCocoa).

**Comment by mzbik** [comment]
One thing to consider: how to handle CPU capture. Is there a way to avoid infinite loops taking you down. With LUA, you have the sources in your dev tree (they're small) and you can easily abort the execution.  Python/Ruby/JS are all a bit harder...

**Comment by trishume** [comment]
It is awesome that @mgax has something working. I think it would be better if the scripting did not require direct interfacing with the objc api.

Maybe if something was passed into the functions like a `currentWindow` parameter and a `slate` object. The objects passed in would have simpler methods in the style of the language being used. The `currentWindow` object encapsulates operations on the focused window and the `slate` object allows the script to do things like query all the windows and show window hints.

Which would make your python example look more like this:

``` python
def left(win,slate):
    new_xy = ((win.x + 10), win.y)
    win.move(new_xy)
```

Or in Lua:

``` lua
function left(win,slate)
  win.move(win.x + 10, win.y)
end
```

**Comment by mzbik** [comment]
Object API saves jgish having to plumb new API each time someone wants a new feature

**Comment by trishume** [comment]
@mzbik he already has to add a configuration parser when adding a new feature, it would actually be easier with an api. The thing with directly accessing the Obj-C constructs is that Slate is already difficult to configure for many people and a hard API wouldn't help.

**Comment by mgax** [comment]
Actually it's quite easy to implement a nice API in the scripting language itself, just wrap the Obj-C method calls with a thin native-looking layer.

**Comment by trishume** [comment]
That is a great way to do it and one possible solution, I just think it should be built in.

**Comment by mzbik** [comment]
Long term, the model needs to be simple enough for people to use but powerful enough for the rest of us.

The trade off is in terms of making something that may require people to whack slate.py when they upgrade. This argues for carefully exposed API from slate and nothing that involves objc.

**Comment by jigish** [comment]
@mgax suggested another option: Javascript. No additional Framework needed, all built in if you use WebViews. Plus the added benefit that it is pretty widely known/used.

**Comment by trishume** [comment]
@jigish is there any API for using the JS engine without a webview? It would be rather hacky to have an invisible webview floating around at all times.

**Comment by jigish** [comment]
@trishume unfortunately there is not. Though it does seem hacky it is the "accepted" way to run JS in objective c lol. Whatever that means :). There is the side benefit of maintaining a persistent context. For example you could save a JS variable in one binding to be used in another that is activated later (I'd use node.js style closures and proper exporting to make sure things don't get crazy). Also from what I remember the memory footprint isn't that bad though I'll make sure to test thoroughly. Also it will be running on the very mature safari JS engine and will benefit from any updates Apple makes to it.

All of this is still not enough to definitely say JS is the way to go, just food for thought :)

**Comment by qmx** [comment]
one can always embed V8 :P

**Comment by trishume** [comment]
One language-neutral and important point to discuss is how to link the scripting language. I can think of three options:
1. Make the entire config file a DSL of that language, maintain backward compatibility with old config files. Like:

``` lua
-- In Lua
config("keyboardLayout", "dvorak")
bind("e","cmd", function(window,slate)
  window.move(10,10)
  slate.showHints("sanetohu")
end)
```

``` ruby
# In Ruby
config :keyboardLayout, :dvorak
bind 'e', :cmd do |window, slate|
  window.move 10,10
  slate.showHints "sanoetuhsnth"
end
```
1. Use a separate file and bind functions from that file like @mgax did with python.
2. Have a custom command that uses an inline script. Like this:

```
bind e:cmd script <<END
  window.move(10,10)
  slate.showHints("aoeuidhtns")
END
bind g:cmd script "window.hide()"
```

**What do people think? I am personally in favor of the DSL approach.**

**Comment by jigish** [comment]
I like the elegance of a DSL as well. Though in some languages _cough_ javascript _cough_ it would just look forced.

**Comment by qmx** [comment]
@jigish why?

``` javascript
config.bind('e', 'cmd', function(window, slate){
    window.move(10,10);
    slate.showHints("why does this looks forced?");
});
```

**Comment by jigish** [comment]
eh I suppose. I guess I just think ruby is prettier :)

coffeescript anyone? ;)

**Comment by trishume** [comment]
Hmmm, I've looked at the API for communicating with JS in a webview and it is pretty terrible even compared to the Ruby embedding APIs. Unless I'm mistaken and there is a better way of communicating than evaling strings and intercepting AJAX requests...

In terms of Ruby I think [mruby](https://github.com/mruby/mruby) might be an option but now that I look at it deeper MacRuby seems like more of an option. Slate could load a user supplied ruby file and add a require to a custom slate library to the top, the library would implement the DSL and use the Obj-C bridge to call the appropriate obj-c api.

Lua has a ton of different bridges to objective-C, any one of which could be used.

**Comment by mzbik** [comment]
And we have a nearly working python instance too ;)

**Comment by mgax** [comment]
+1 on the DSL approach. It could call out to external code if you really want to, so you get the benefit of the separate-file approach. And we can write a conversion script to upgrade people's config files. For Python there is the decorator syntax:

```
@config.bind('e', 'cmd')
def the_e_key(window, slate):
    window.move(10,10)
    slate.showHints("asdf")
```

@trishume i think http://will.thimbleby.net/script/ describes a nice approach to call into Objective-C from JS.

**Comment by mzbik** [comment]
+1 on the DSL too.  My personal take is that Ruby/Python win. LUA less so.  JS doesn't quite cut it.

Again, my big concern is being able to effectively deal with infinite loops in the callouts.

**Comment by trishume** [comment]
Hmmmm, I have to figure out how to link to MacRuby, I'm going to try including the framework from the MacRuby distribution, I really don't want to have to compile it.

I might just fiddle with @mgax's python branch or @qmx's lua branch.

I've looked at the Slate code and in most cases the current operation objects can be used unmodified. The only problem is the move, hint and grid operations rely on ExpressionPoint objects, either the DSL library can create dummy expressionpoint objects of some subclass or the code can be modified to not rely on ExpressionPoint objects.

**Comment by trishume** [comment]
I've created a branch of my fork for MacRuby support.

My first step will be useful for a DSL of any language, I'm going to try and extract a subclass of SlateConfig that does all the parsing. That way the way the same API can be used for accessing config variables and bindings no matter what kind of file is used.

**Comment by trishume** [comment]
I have created a branch of my Slate fork where I have extracted a subclass of `SlateConfig`. This allows for other subclasses to parse config files in a different way, such as a DSL.

I am going to try and create a subclass of SlateConfig that uses a MacRuby DSL for configuration in my `ruby` branch, the `getInstance` method will create a `SlateRubyConfig` if a `~/.slate.rb` file exists and otherwise it will create a `SlateFileConfig`.

**Comment by mgax** [comment]
In JavaScript there's a nice way to write event handlers declaratively. Syntax borrowed [from Backbone](http://backbonejs.org/#View-delegateEvents).

```
events = {
    'e:cmd,shift': function(evt) {
        slate.getCurrentWindow().move(10, 10);
        slate.showHints("why does this looks forced?");
    },
    'esc:cmd': 'hint',
    'esc:ctrl': 'grid'
};
```

So you have a big dictionary, with keys similar to the bindings in the current config format. Values are either functions (will be called) or strings (can be interpreted as commands of some sort).

**Comment by mzbik** [comment]
What baggage will we need to embed JS? Windows, etc?

On Dec 7, 2012, at 7:14 AM, "Alex Morega" <notifications@github.com<mailto:notifications@github.com>> wrote:

In JavaScript there's a nice way to write event handlers declaratively. Syntax borrowed from Backbonehttp://backbonejs.org/#View-delegateEvents.

events = {
    'e:cmd,shift': function(evt) {
        slate.getCurrentWindow().move(10, 10);
        slate.showHints("why does this looks forced?");
    },
    'esc:cmd': 'hint',
    'esc:ctrl': 'grid'
};

So you have a big dictionary, with keys similar to the bindings in the current config format. Values are either functions (will be called) or strings (can be interpreted as commands of some sort).

**Comment by trishume** [comment]
Using MacRuby requires embedding MacRuby.framework, which is around 10mb.

**Comment by mzbik** [comment]
Sounds like Python/LUA might be winning...

**Comment by trishume** [comment]
I'm not sure about that, people seem to like the idea of a DSL and that is one of Ruby's specialties. I am currently working on implementing a DSL in MacRuby, which shouldn't be too hard. Embedding the MacRuby framework isn't that bad.

Looking back at comments, 4 people (myself included) seem to favor Ruby if it is possible, 2 people favor Python and 2 people favor Lua. If I interpret people's comments right.

I suggest that we build some prototypes and decide which one we like best, I'm building a MacRuby prototype, @mgax may want to build a prototype of a Python DSL and I'm not sure if anyone would be interested in doing other languages.

**Comment by muescha** [comment]
How about a language independent solution like the vert.x ( http://vertx.io/ )

And because i think its a general problem, interesting for other apps, it can be a seperate framework which can be embedded i different app

**Comment by mzbik** [comment]
A framework is fine, just that you need >some< language in order to actually do something.

The primary goal was to allow for sophisticated (read: user-programmed) event handlers. Then, Tristan proposed being able to have a DSL do the configuration too.  Both are good goals.  Now,  the issues are:
1. Is the DSL for configuration different from the programmability language?  If so, I should think it would need a huge justification.  The complexity of supporting two languages (both implementation and FAQ) seems to outweigh the idea of two.
2. Assuming there is one language, do we invent one of our own? IT doesn't matter if it's a subset of another known language, it'll just be different. Again, unless someone has a huge justification for this, we should go with something well-known in its entirety.
3. Assuming that we will be using something well-known, what baggage will the language implementation bring in? From the time a keystroke is received to when the effects of the event handler are fully visible, it has to be fast. You can't page in megabytes.  You can't run a garbage collector multiple times. Are there other programming-model impediments that we would bring in?
4. And then there's the features of the implementation.  Do we want some sort of OO language?  Is type-safety relevant? What about other features of the runtime? Is network access important?  File system?  Multithreading?

**Comment by trishume** [comment]
The DSL would definitely be in the scripting language, and the language would definitely be a popular one. There are options that would be really easy to embed and use like F-Script and Nu but they are not well known.

MacRuby is LLVM compiled to some extent and uses Objective-C classes directly so there is little to no lag translating the objects.

The server idea is interesting and has some significant advantages, I definitely agree that it would have to be forked into some separate Daemon or something though. It is an interesting idea for a project, maybe a fork of Slate, a socket interface for the mac accessibility API or something. However, that is something to discuss maybe in another issue/fork.

The advantage of a language embedded right in is it allows a DSL so users can configure Slate in a familiar language, it would also make adding new commands slightly easier because no parsing code would be required. However, it also allows for advanced users to code more complex behaviours.

I am a bit busy right now but maybe in a week I will start working on my MacRuby version and see what I can do and what problems I run into.

**Comment by trishume** [comment]
Hmmmm, MacRuby has the baggage that it requires the app and all frameworks to be compiled with GC.
Unfortunately this functionality is deprecated in OSX 10.8 but still works fine.

I think I could port Slate to GC and use the GC version of Sparkle without difficulty, I am mainly worried about future dependencies and the deprecation.

MacRuby development is slow right now because of all the work on RubyMotion but apparently the algorithms that allow MacRuby to be used without GC will be merged into MacRuby eventually so this won't always be a problem.

I'm going to try enabling GC and see how it goes.

**Comment by mzbik** [comment]
Very valid concern.

**Comment by trishume** [comment]
gg MacRuby. :rage: 

I tried to enable GC and apparently JSONKit does not support GC being enabled, I also get a million warnings.
To top it off every article I read on the web on how to solve these problems says "don't use GC".

I will now either try to use one of the prerelease builds of mruby or just give up on Ruby and use Lua or Python to implement the DSL.

**Comment by mgax** [comment]
Maybe JavaScript is a good choice. If I find some time I'll try to write some bindings.

**Comment by mgax** [comment]
Here is a working branch with JavaScript bindings: https://github.com/mgax/slate/tree/javascript and a build: http://grep.ro/quickpub/slate/2013-01-19/.

In addition to `~/.slate`, you can create `~/.slate.js`, which gets executed in a WebScripting context. There is a `slate` global object with a few methods:
- `log(message)` - print a message using NSLog.
- `bind(keystroke, callback, repeat)` - register a binding that will invoke the given JavaScript function.
- `resize(x, y)`, `nudge(x, y)`, `focus(x, y)` - perform these operations.
- `relaunch()` - restart Slate to reload configuration.

This is what a configuration file might look like: https://gist.github.com/4569350.

The next step is to implement missing operations, and to simplify the syntax, so you can write:

```
slate.bind('l:cmd,ctrl,alt', 'resize +10 +0', true); 
slate.bind('r:cmd,shift,alt', 'relaunch');
```

Or even better:

```
slate.bindAll({
    'l:cmd,ctrl,alt': 'resize +10 +0 repeat',
    'r:cmd,shift,alt': function() { slate.log("relaunching"); slate.relaunch(); }
});
```

But scripting only gets interesting when you can write some logic in the callback, and for that, you need access to data about current windows and screens. What are some obvious needs here?

**Comment by jigish** [comment]
@mgax - Nice! I was planning on hacking on slate a bunch this weekend, would love to pull this into to mainline so I can implement some of the stuff I was thinking about as well. Couple things I wanted to do:
- instead of `'l:cmd,ctrl,alt'` as a parameter, I'd like to start deconstructing the slate syntax so it would be more like `slate.bind('l', ['cmd', 'ctrl', 'alt'], function() { slate.resize(10, 0) }, true);`. I feel like doing this will make adding more complex features easier in the future. We'd keep support for the original syntax of course, but some of the new complex features would be only accessible if you use the javascript syntax.
- implement a bunch of variables in the slate object for use within the callback like current window stuff, current screen stuff, current screen configuration stuff, etc.

**Comment by jigish** [comment]
Also, I'm thinking I'll pull in a convenience JS library like http://underscorejs.org/ which should make life easier.

**Comment by trishume** [comment]
@mgax that is awesome! Right now it is kind of inefficient and ugly since it creates a new operation from a string every time you call one of the methods.

I think a DSL would need a refactoring of the way some operations work and other DSL methods could directly call AccessibilityWrapper methods.

**Comment by jigish** [comment]
Yes, I agree with @trishume - it would be nice to have a `slate.operation()` function that creates an operation for use in later bindings. that way you don't have to keep creating new ones later. also, the ability to specify a function as an argument (say the `x` value) to an operation will allow you to create a dynamic operation that can change based on the context without having to create a brand new operation.

now I'm getting super juiced about this. please excuse me while I hack away.

**Comment by muescha** [comment]
disclaimer: i dont know if this should be separate issues/feature requests or still implement and i dont know it

1) key sequences

is it also possible to add key sequences?

like: 

['k:cmd,alt' , 'a', 'x']
['k:cmd,alt' , '1']

2) slate Shortcut Prefix

let me somehow define a general intro shortcut to activate slate, so all my slate commands overwrite the shortcuts of other apps.

3) key definitions

because i dont like strings as definitions, can we somehow get rid of the 'l:cmd,ctrl,alt' as string syntax? i like it more as constants or objects? or is this too much overconfigurated?

somehow like this:
Key.a.cmd.ctrl.alt
Key('a').cmd.ctrl.alt
key.enter.cmd

4) access to all child windows?

use case: i have a firefox open with many (child) windows - now i like to set the size not only for the current active child window, but for all childwindows of firefox?

additional: for all apps(+child windows) on current screen 
additional: on all screens

is this with the dsl then posssible?

**Comment by jigish** [comment]
@muescha 

1) Can I have an example of how this would be used? Are you saying that a sequence of keys would trigger a binding?
2) you mean Modal Bindings?
3) I think this is a bit overdone. What would make sense is to wrap the entire keystroke in a class which would make it easier to support modal bindings.
4) yah this is what I would want to do. the `slate` object would have the information about the current window and maybe with an option on the method we could add the information about all windows on the screen. I say an option on the method because it would affect performance.

**Comment by jigish** [comment]
@mgax - I hope you don't mind me merging your javascript branch to master and hacking on it. I have tons of time today and would love to get a lot of this squared away before a push a new version :)

**Comment by muescha** [comment]
1) yes sequence should trigger a binding

Example 1:
like to combine some things:

``` ruby
'a:cmd,alt','1' - left size big
'a:cmd,alt','2' - left size middle
'a:cmd,alt','3' - left size small
```

Example 2:
because some shortcuts overwrite my app shortcuts i would like to have a sequence to activate it 

this:

``` ruby
'k:cmd,alt'
'a:cmd,alt'
```

i would hide all shortcuts behind a starting shorcut `'s:cmd,alt'`

``` ruby
['s:cmd,alt', 'k']
['s:cmd,alt', 'a']
```

or if i can have a dsl i would sourround it with a block:

``` ruby
with_key 's:cmd,alt' do
   key 'k' ...  #-> ['s:cmd,alt', 'k']
   key 'a' ...  #-> ['s:cmd,alt', 'a']
end
```

or example 1 written with dsl:

``` ruby
with_key 's:cmd,alt' do
  with_key 'a' do
    key '1' ...  #-> ['s:cmd,alt', 'a', '1']
    key '2' ...  #-> ['s:cmd,alt', 'a', '2']
    key '3' ...  #-> ['s:cmd,alt', 'a', '3']
  end
end
```

or also with a dsl i like to do

``` ruby
key 'a:cmd,alt'
key 'b:cmd,alt'


with_modifier 'cmd,alt' do
  key 'a'   # --> 'a:cmd,alt' 
  key 'b'   # --> 'b:cmd,alt' 
end
```

2) i think this can be done with sequence. see (1)

3) it was just to avoit misspellings something in text ;-)

4) something like `window.childwindows` should give an array of child windows back

**Comment by mgax** [comment]
@jigish Go ahead and merge it, that was the point :) I was also thinking about pulling in Underscore.

Instantiating an Operation for every callback is not ideal, but we can worry about performance later, once we figure out what's possible with scripting, and where it's going.

I actually prefer string key definitions, they are shorter and more expressive, reminiscent of CSS selectors. The whole binding syntax is inspired by Backbone [event delegation](http://backbonejs.org/#View-delegateEvents) for views.

What sort of extra bindings do you have in mind? Here's one possible approach: Keep a simple API for JavaScript, basically a thin wrapper around `RegisterEventHotKey` and `activateBinding:isRepeat:`, and implement more complex constructs in JavaScript, where it's easier to experiment.

**Comment by trishume** [comment]
I think a cool way to do modal/flexible bindings would be to have an api function in JS that allows you to remove bindings. That way you could implement your own modal bindings as well as other things like pressing things in quick succession.

**Comment by mgax** [comment]
@trishume Yes, that's precisely the idea, but the Slate bindings implementation doesn't make it easy. I have an idea how to make it work though. Also you need a working `setTimeout` implementation, but that should be no problem.

**Comment by mgax** [comment]
I've been experimenting in my [javascript-kvc branch](https://github.com/mgax/slate/tree/javascript-kvc) with a JS-friendly way to access application and window information, based on [KVC](https://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/KeyValueCoding/Articles/KeyValueCoding.html) (key-value coding), as suggested by Apple's documentation on [WebScripting](http://developer.apple.com/library/mac/#documentation/Cocoa/Reference/WebKit/Protocols/WebScripting_Protocol/Reference/Reference.html#//apple_ref/occ/cat/WebScripting). For example:

```
slate.bind('t:cmd,ctrl,shift', function() {
    // get current application, print its name
    var app = _controller.focusedApplication();
    slate.log("Application:", app.name());

    // get current window, print its title
    var win = app.focusedWindow();
    slate.log("Window:", win.title());

    // get window's size and shrink it by 10px
    var size = slate.unpack(win.size());
    win.setSize_(slate.pack({
        width: size.width - 10,
        height: size.height - 10
    }));
});
```

The `pack` and `unpack` methods are necessary because `NSDictionary` is not automatically converted to a JS object. [Here](http://grep.ro/quickpub/slate/2013-01-21/) is a build of the `javascript-kvc` branch.

**Comment by jigish** [comment]
Interesting. I've been refactoring all the operations and such to make it easier to access through JS myself. Focusing more on the operations themselves and less on free-form function bindings. Was planning on doing something like this next but glad you got to it :). Once I finish implementing all the operations, I'll check this stuff out and see if I can do a clean merge.

**Comment by jigish** [comment]
btw, a little taste of what I've done:

```
var mtest = false;
var move = slate.operation("move", {
  "x" : "screenOriginX",
  "y" : function() {
    mtest = !mtest;
    return mtest ? "screenOriginY+screenSizeY/2" : "screenOriginY";
  },
  "width" : "screenSizeX/2",
  "height" : "screenSizeY/2"
});
slate.bind("1:ctrl", function() { move.run() }, true);
// or simply:
slate.bind("2:ctrl", move, true);
```

Sort of changed around the syntax and such to make it easier to add new operations. Each operation can be created using the string name then an options hash. The hash can contain functions which will be evaluated at run time or constants which will be stored into the operation at config time. `slate.operation` will instantiate an operation and calling `run` on the returned object will run the operation. This way we don't waste time recreating operations over and over.

**Comment by jigish** [comment]
ok just pushed my changes. theres a ton of stuff there. here is what is left to make this fully functional (so you only need the `.slate.js`):
- include @mgax's stuff to expose current window info, screen info, and other things
- add the other directives (`config`, `layout`, `default`, `source`)
- verify/add support for modal keys and implement modal toggle

some additional ideas/notes:
- `config` locally. i.e. setting a config for a particular binding and not for others
- `loop` operation. only available from js. will execute the given operation or function for every window (you'll be able to get the current window info from the function). should probably add an option to only loop through windows in the current app.
- `layout` should really be easier in js than it currently is in the default syntax. I'll try to clean it up when I implement it in js. Ideally, you should be able to call non-movement operations from within the layout (for example `hide`) without jumping through hoops and the various options should be easier to specify.
- `source` should be able to source both normal `.slate` files and `.slate.js` files.

I'm going to start with `config` since it should be really simple.

**Comment by jigish** [comment]
also, I'm going to start documenting this new stuff on the Wiki instead of the readme. There is probably going to be _way_ too much content to add to the readme.

**Comment by mzbik** [comment]
Two questions:
1. How are Unhandled exceptions handled/logged? What does the end user see?
2. Ditto for infinite loops?

On Jan 20, 2013, at 11:16 PM, "Jigish Patel" <notifications@github.com<mailto:notifications@github.com>> wrote:

also, I'm going to start documenting this new stuff on the Wiki instead of the readme. There is probably going to be way too much content to add to the readme.

**Comment by jigish** [comment]
@mzbik right now there is some basic handling of exceptions. it _should_ display an alert. Syntax errors are a bit more tricky. I need to figure out a way to deal with them. Infinite loops I'm not really show what the best way to handle is. To be completely honest I'm very much of the opinion that there isn't really much of a point to jumping through hoops to prevent people from doing stupid things. If there is an infinite loop, slate will hang and the user will figure it out or post an issue which can be debugged. From what I can tell, the only way to detect an infinite loop would be to time the execution of the js and break if it takes "too long". I'm not convinced that this is a good idea.

**Comment by jigish** [comment]
also to clarify -- by "syntax errors are a bit more tricky" i mean things like undefined variables will show an alert but a missing comma will fail silently and show no indication to the user. I need to figure out a way to detect the syntax errors. I haven't really spent much time on it though. If apple doesn't have any APIs to detect it one idea is to try to run  a very simple function like `function() { return true; }` after importing the user's JS. If the function fails to run or does not return true, I know that the user has some error in their JS.

**Comment by mzbik** [comment]
It's not a matter of prevention, but of not crashing enough of the system to discourage use.

For infinite loop, if we can hook the js op code  dispatch, we can establish a configurable limit per keystroke

On Jan 21, 2013, at 12:06 AM, "Jigish Patel" <notifications@github.com<mailto:notifications@github.com>> wrote:

@mzbikhttps://github.com/mzbik right now there is some basic handling of exceptions. it should display an alert. Syntax errors are a bit more tricky. I need to figure out a way to deal with them. Infinite loops I'm not really show what the best way to handle is. To be completely honest I'm very much of the opinion that there isn't really much of a point to jumping through hoops to prevent people from doing stupid things. If there is an infinite loop, slate will hang and the user will figure it out or post an issue which can be debugged. From what I can tell, the only way to detect an infinite loop would be to time the execution of the js and break if it takes "too long". I'm not convinced that this is a good idea.

**Comment by jigish** [comment]
ok. this is finally done. now I just need to document the shit out of it. next release (1.0.19) will have the code. I'm going to mark this feature as "beta" because it is so much code that I haven't had the time to completely test it. I'm sure there are tons of corner cases that I've missed. look for updates on the wiki with documentation.

things that are not done:
- `config` things locally - not done because it is a feature in itself. the way configs work is that once they are set, a lot of them can't be reset.
- worrying about infinite loops - eh, if the user codes up an infinite loop and hangs slate they can deal with it. I have no intention of jumping through hoops to make sure the user doesn't do silly things. I do that enough at work :)

**Comment by mzbik** [comment]
The whole infinite loop thing only exists as a 'can the use hose himself to the point where a reboot/safe-boot is the only recourse'. If the user has a well-defined 'exit strategy', then we're cool.

On Jan 23, 2013, at 4:37 PM, "Jigish Patel" <notifications@github.com<mailto:notifications@github.com>> wrote:

ok. this is finally done. now I just need to document the shit out of it. next release (1.0.19) will have the code. I'm going to mark this feature as "beta" because it is so much code that I haven't had the time to completely test it. I'm sure there are tons of corner cases that I've missed. look for updates on the wiki with documentation.

things that are not done:
-   config things locally - not done because it is a feature in itself. the way configs work is that once they are set, a lot of them can't be reset.
-   worrying about infinite loops - eh, if the user codes up an infinite loop and hangs slate they can deal with it. I have no intention of jumping through hoops to make sure the user doesn't do silly things. I do that enough at work :)

**Comment by jigish** [comment]
totally understand the reasoning for worrying about infinite loops, but honestly I feel like it will be too much trouble than what it is worth. Unless the user literally writes something like:

```
while (true) {
  slate.log("HAHAHA I MADE AN INFINITE LOOP");
}
```

It'll be very hard for there to be an infinite loop in javascript.

**Comment by jigish** [comment]
I have created a wiki page here: https://github.com/jigish/slate/wiki/JavaScript-Configs

I'll be adding to it when I get a chance to document all this stuff. I've added a skeleton which has the complete list of methods on the `slate` object. Anyone interested is welcome to check it out and let me know if there is anything I may have missed.

**Comment by trishume** [comment]
@mzbik Infinite loops should not force a restart, all you have to do is force quit slate, the OS will not hang.

Adding a time limit stops cool behaviors like waiting for the user to press additional keys and things like that.

Also, awesome work @jigish and @mgax, I had hoped to contribute with MacRuby but the stupid GC incompatibility thwarted me :(

**Comment by mzbik** [comment]
Thanks, Tristan/Jigish.

Here's a question: is there a way to manipulate window/space relationships too?

On Jan 24, 2013, at 15:17, "Tristan Hume" <notifications@github.com<mailto:notifications@github.com>> wrote:

@mzbikhttps://github.com/mzbik Infinite loops should not force a restart, all you have to do is force quit slate, the OS will not hang.

Adding a time limit stops cool behaviors like waiting for the user to press additional keys and things like that.

Also, awesome work @jigishhttps://github.com/jigish and @mgaxhttps://github.com/mgax, I had hoped to contribute with MacRuby but the stupid GC incompatibility thwarted me :(

**Comment by jigish** [comment]
@mzbik - Spaces Support is being tracked on Issue #78

**Comment by jigish** [comment]
For the record, I should be finished documenting everything in the wiki by EOD today. Most of it is done as of right now. All that is left is Expressions, the Window Object, the Application Object and the Screen Object. I'll also probably add a couple convenience functions on the Operation object tonight as well as aliasing the Window, Application, and Screen object functions (some of them are irritatingly long).

**Comment by jigish** [comment]
Finally done documenting.

**Comment by sdegutis** [comment]
@mgax, @mgax, @jigish, @trishume, @wez:

I just looked at the scripting-language discussion above, and I have some information that may help.

Recently I wrote my own window manager called AppGrid that was along the lines of Spectacle.app but with slightly different actions. Then I wanted to see if I can add scripting to it, so I copied Slate's approach of embedding JS. (However I used JSCocoa which wraps JavaScriptCore directly rather than going through a WebView.) And I renamed the app to [Zephyros](https://github.com/sdegutis/zephyros).

This worked fine, but I wanted to try adding Ruby too. I looked into MacRuby, and as noted above, realized that it only works in GC-enabled apps, and my app used ARC. And RubyCocoa was deprecated. So I just compiled Ruby 2.0 and embedded it directly. It was easy enough to do, took just one weekend.

But then I wanted to embed Python. And Lua. And F-Script, and Nu. But I realized this wouldn't scale, because the executable was getting really big. And I wanted to script it in Go and Rust and Elixir, but you can't embed these into an ObjC app. So I concluded that embedding was the wrong approach if my goal was to extend it via more than one language.

So I came up with what I think is a good compromise. The app acts like a server, listening on a local unix socket, and scripts are written as clients that connect and send messages and receive responses. The protocol is a simple JSON protocol that mimics ObjC method calls, so you would send Zephyros `[message_id_1, my_window_id, "title"]` and it would send back `[message_id_1, "Terminal.app - bash"]` for example. Here's some [more details about it](https://github.com/sdegutis/zephyros/blob/master/Docs/TCP.md).

The performance doesn't suffer from this approach. Even on my slower Mac, it performs just as good as it did when it was embedded. The overhead of using unix sockets and parsing JSON doesn't seem to be much higher than the overhead of translating JS <-> ObjC using a WebView. But admittedly you'd have two processes running instead of just one. However that may be a pro rather than a con, depending on how you look at it.

What do you think of taking this approach in Slate.app? It might involve a little internal refactoring, but I think allowing Slate to be scripted in many languages would be really cool.
